# Generated by Django 3.2.16 on 2025-12-22 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('occasion', models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('other', 'Другое')], max_length=50, verbose_name='Выбор повода')),
                ('description', models.TextField(verbose_name='Описание')),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Конечная сумма')),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Собранная сумма')),
                ('image', models.ImageField(upload_to='collects/images/', verbose_name='Изображение')),
                ('end_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата окончания сбора')),
            ],
        ),
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='collects.collect')),
            ],
        ),
    ]
